dist: bionic
language: cpp
cache: ccache
os: linux

compiler: "clang-9"

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/build

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - clang-9
      - cmake
      - python3
      - python3-pip
      - python3-dev
      - python3-setuptools
      - tbb-dev
      - tbb2



install:
  - pip3 install --user conan conan_package_tools cmake urllib3


script:
  - cmake . -Bbuild -DCMAKE_BUILD_TYPE=Debug && cmake --build build -- -j2

