dist: bionic
language: cpp
cache: ccache
os: linux

compiler: clang++-9

cache:
  directories:
    - $HOME/.conan/data

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - clang-9
      - g++-9
      - cmake
      - python3
      - python3-pip
      - python3-dev
      - python3-setuptools
      - libtbb-dev
      - libtbb2
      - libc++-dev



install:
  - pip3 install --user conan conan_package_tools cmake urllib3


script:
  - cmake . -Bbuild -DCMAKE_BUILD_TYPE=Release && cmake --build build -- -j2

